# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://caius.brindescu.com/
baseurl: ""
title: Caius Brindescu
author: Caius Brindescu
description: Personal blog and resume
avatar: me.jpeg
email: caius@brindescu.com
github: caiusb # username
twitter: caiusbrindescu
#linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-44238746-2 


# needed for travis-ci build
exclude: [vendor]
